# Generated by Django 3.2.7 on 2021-09-15 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish_name', models.CharField(max_length=30)),
                ('dish_type', models.CharField(max_length=30)),
                ('caixi', models.CharField(max_length=30)),
                ('flavor', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TrainingItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nick_name', models.CharField(max_length=30)),
                ('gender', models.CharField(max_length=2)),
                ('state', models.CharField(max_length=100)),
                ('dish_name', models.CharField(max_length=30)),
                ('dish_type', models.CharField(max_length=30)),
                ('caixi', models.CharField(max_length=30)),
                ('flavor', models.CharField(max_length=30)),
                ('rank', models.IntegerField()),
            ],
        ),
    ]
